<?php
namespace app\admin\controller;
use think\Controller;
//校验用户是否登录

class Base extends Controller
{
    //初始化方法

    public function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub
        //判断用户是否登录
        if(!$this->isLogin()){
            return $this->redirect('login/index');
        }
    }

    //判断是否登录
    public function isLogin(){
        $adminer = session(config('admin.session_admin'));
        if($adminer){
            return true;
        }
        return false;
    }























}
